# Generated by Django 4.2.6 on 2023-10-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_customuser_profile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
