# Generated by Django 4.2.6 on 2023-10-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Ladies', 'Ladies')], max_length=20)),
                ('water_facilities', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('proximity_to_grocery_stores', models.BooleanField(default=False)),
                ('nearest_transportation', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train')], max_length=10)),
                ('room_type', models.CharField(choices=[('Individual', 'Individual'), ('Halltype', 'Hall-type')], max_length=20)),
                ('max_people', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('extra_info', models.TextField()),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RentalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rental_type', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('other', 'Other')], max_length=20)),
                ('water_facilities', models.BooleanField(default=False)),
                ('electricity', models.BooleanField(default=False)),
                ('proximity_to_grocery_stores', models.BooleanField(default=False)),
                ('nearest_transportation', models.CharField(choices=[('bus', 'Bus'), ('train', 'Train')], max_length=10)),
                ('max_people', models.PositiveIntegerField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=100)),
                ('extra_info', models.TextField()),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('has_whatsapp', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
