# Generated by Django 4.2.6 on 2023-10-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0005_hostelinformation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
    ]
