# Generated by Django 4.2.6 on 2023-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0007_hostelinformation_price_rentalinformation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinformation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
